
services:
  countdown-timer:
    build: .
    container_name: countdown-timer-app
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      # Optional: Mount logs for debugging
      - ./logs:/var/log/nginx
    networks:
      - countdown-network

networks:
  countdown-network:
    driver: bridge 